# Generated by Django 4.1.2 on 2022-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Ambassador",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="ambassador",
        ),
        migrations.AlterField(
            model_name="job",
            name="job_id",
            field=models.IntegerField(null=True),
        ),
    ]
